import fs from "fs";
import path from "path";
import type { Article, Collection } from "../src/content/types";
import { cleanArticle } from "../src/utils/clean-article";

const supportDocsDir = path.resolve(import.meta.dir, "..", "..", "support-docs");
const treePath = path.join(supportDocsDir, "_tree.json");
const manifestPath = path.join(supportDocsDir, "_manifest.json");
const outPath = path.resolve(import.meta.dir, "..", "src", "content", "manifest.ts");

type TreeCollection = {
  path: string;
  source_file?: string;
  title?: string;
  source_url?: string;
  intercom_collection_id?: string;
  source_slug?: string;
  metadata_stub?: boolean;
};

type ManifestData = {
  files: string[];
};

function readJson<T>(p: string): T {
  return JSON.parse(fs.readFileSync(p, "utf8")) as T;
}

function parseFrontmatter(content: string): {
  fm: Record<string, string>;
  body: string;
} {
  if (!content.startsWith("---")) return { fm: {}, body: content };
  const lines = content.split("\n");
  if (lines[0].trim() !== "---") return { fm: {}, body: content };
  let i = 1;
  const fmLines: string[] = [];
  while (i < lines.length && lines[i].trim() !== "---") {
    fmLines.push(lines[i]);
    i++;
  }
  const fm: Record<string, string> = {};
  for (const line of fmLines) {
    const idx = line.indexOf(":");
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    const val = line.slice(idx + 1).trim();
    if (key) fm[key] = val;
  }
  const body = lines.slice(i + 1).join("\n");
  return { fm, body };
}

function firstH1(body: string): string | null {
  for (const line of body.split("\n")) {
    const m = line.match(/^#\s+(.+?)\s*$/);
    if (m) return m[1].trim();
  }
  return null;
}

function parentOf(p: string): string | null {
  const idx = p.lastIndexOf("/");
  return idx === -1 ? null : p.slice(0, idx);
}

function main() {
  const tree = readJson<{ collections: TreeCollection[] }>(treePath);
  const manifestData = readJson<ManifestData>(manifestPath);

  const collections: Collection[] = tree.collections.map((c) => {
    const parentPath = parentOf(c.path);
    let title = c.title ?? null;
    if (!title) {
      try {
        const stubContent = fs.readFileSync(
          path.join(supportDocsDir, c.path, "_collection.md"),
          "utf8",
        );
        title = firstH1(parseFrontmatter(stubContent).body) ?? null;
      } catch {
        title = null;
      }
    }
    return {
      path: c.path,
      title: title ?? c.path,
      sourceUrl: c.source_url ?? null,
      sourceSlug: c.source_slug ?? null,
      intercomCollectionId: c.intercom_collection_id ?? null,
      metadataStub: Boolean(c.metadata_stub),
      parentPath,
      childCollectionPaths: [],
      articleSlugs: [],
    };
  });

  for (const c of collections) {
    c.childCollectionPaths = collections
      .filter((c2) => c2.parentPath === c.path)
      .map((c2) => c2.path);
  }

  const articles: Article[] = [];
  const articlesBySlug: Record<string, string> = {};
  let skippedCollectionMd = 0;
  let skippedUncategorized = 0;
  let missingFile = 0;

  for (const relPath of manifestData.files) {
    const segments = relPath.split("/");
    if (path.basename(relPath) === "_collection.md") {
      skippedCollectionMd++;
      continue;
    }
    if (segments.includes("_uncategorized")) {
      skippedUncategorized++;
      continue;
    }
    if (relPath === "_tree.json" || relPath === "_manifest.json") continue;

    const absPath = path.join(supportDocsDir, relPath);
    let content: string;
    try {
      content = fs.readFileSync(absPath, "utf8");
    } catch {
      missingFile++;
      continue;
    }

    const { fm, body } = parseFrontmatter(content);
    const cleanedBody = cleanArticle(body);
    const slug = path.basename(relPath, ".md");
    const collectionPath = path.dirname(relPath).split(path.sep).join("/");
    const title = firstH1(body) ?? slug;

    articles.push({
      slug,
      title,
      sourceUrl: fm.source_url ?? null,
      scraped: fm.scraped ?? null,
      collectionPath,
      body: cleanedBody,
    });
    articlesBySlug[slug] = cleanedBody;

    const col = collections.find((c) => c.path === collectionPath);
    if (col) col.articleSlugs.push(slug);
  }

  const buildTimestamp = new Date().toISOString();
  const articlesPublic = articles.map((a) => ({
    slug: a.slug,
    title: a.title,
    sourceUrl: a.sourceUrl,
    scraped: a.scraped,
    collectionPath: a.collectionPath,
  }));

  const output =
    "/* eslint-disable */\n" +
    "// @generated by scripts/build-content.ts — do not edit manually\n" +
    'import type { Article, Collection } from "./types";\n\n' +
    `export const collections: Collection[] = ${JSON.stringify(collections)} as Collection[];\n\n` +
    `export const articles: Omit<Article, "body">[] = ${JSON.stringify(articlesPublic)} as Omit<Article, "body">[];\n\n` +
    `export const articlesBySlug: Record<string, string> = ${JSON.stringify(articlesBySlug)};\n\n` +
    "export const manifest = {\n" +
    "  collections,\n" +
    "  articles,\n" +
    `  buildTimestamp: ${JSON.stringify(buildTimestamp)},\n` +
    "};\n";

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, output, "utf8");

  console.log(`Collections: ${collections.length}`);
  console.log(`Articles: ${articles.length}`);
  console.log(`articlesBySlug keys: ${Object.keys(articlesBySlug).length}`);
  console.log(`Skipped _collection.md: ${skippedCollectionMd}`);
  console.log(`Skipped _uncategorized: ${skippedUncategorized}`);
  console.log(`Missing files on disk: ${missingFile}`);
  console.log(`Output: ${outPath}`);
}

main();
