name: Setup s3cmd for deploying to S3

inputs:
  access_key:
    required: true
  secret_key:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up S3cmd cli tool
      uses: s3-actions/s3cmd@558ab259e985802479fab6cfd7453bd74b45bc5b # v2.0.1
      with:
        provider: aws
        region: "us-east-1"
        access_key: ${{ inputs.access_key }}
        secret_key: ${{ inputs.secret_key }}
