name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dockerImage:
    uses: team-telnyx/infra-ci-gha-workflows/.github/workflows/dockerImage.yml@latest
    secrets: inherit
